bugfixes:
  - mysql_db, mysql_replication - mask passwords in return values (``executed_commands`` and ``queries``) instead of relying on Ansible's ``no_log`` masking (https://github.com/ansible-collections/ansible.mariadb/pull/31).
